steps:
- id: Build-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/compute-service:$SHORT_SHA', '.']
  timeout: 900s

- id: Push-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/compute-service:$SHORT_SHA']
  timeout: 900s

- id: Cloud-run
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta',
              'run',
              'deploy',
              'compute-service',
              '--image',
              'gcr.io/$PROJECT_ID/compute-service',
              '--region',
              'us-central1',
              '--platform',
              'managed',
              '--allow-unauthenticated']
  timeout: 900s
images:
- gcr.io/$PROJECT_ID/compute-service:$SHORT_SHA