version: "3.8"

services:  
  compute-service-go:
    container_name: compute-service-go
    build: .
    ports: 
      - 8080:8080
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    restart: on-failure