name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull-test-deploy
      uses: appleboy/ssh-action@master
      with:
        host: 34.28.156.191
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        port: 22
        script: |
          cd app
          git pull origin master
          sudo docker-compose up