name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull-test-deploy
      uses: actions/checkout@v2
      uses: google-github-actions/setup-gcloud@master
      with:
        version: "290.0.1"
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        script: |
          cd app
          git pull origin master
          docker compose up -d --build